# Generated by Django 5.2.9 on 2025-12-19 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_kcal', models.FloatField(default=0)),
                ('total_carb', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('total_sugar', models.FloatField(default=0)),
                ('total_sodium', models.FloatField(default=0)),
                ('condition_emoji', models.CharField(blank=True, max_length=10)),
                ('supplement_taken', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='records.dayrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('burned_kcal', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='records.dayrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('grams', models.FloatField(default=0)),
                ('kcal', models.FloatField(default=0)),
                ('carb', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='records.dayrecord')),
            ],
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField()),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='records.dayrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='dayrecord',
            index=models.Index(fields=['user', 'date'], name='records_day_user_id_9d9181_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dayrecord',
            unique_together={('user', 'date')},
        ),
    ]
