# Generated by Django 5.2.9 on 2025-12-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayrecord',
            name='supplement_taken',
        ),
        migrations.AddField(
            model_name='dayrecord',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dayrecord',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dayrecord',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dayrecord',
            name='nutrition',
            field=models.BooleanField(default=False),
        ),
    ]
