# Generated by Django 5.2.9 on 2025-12-19 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('per_100g_kcal', models.FloatField(default=0)),
                ('per_100g_carb', models.FloatField(default=0)),
                ('per_100g_protein', models.FloatField(default=0)),
                ('per_100g_fat', models.FloatField(default=0)),
                ('per_100g_sugar', models.FloatField(default=0)),
                ('per_100g_sodium', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('per_100g_kcal', models.FloatField(default=0)),
                ('per_100g_carb', models.FloatField(default=0)),
                ('per_100g_protein', models.FloatField(default=0)),
                ('per_100g_fat', models.FloatField(default=0)),
                ('per_100g_sugar', models.FloatField(default=0)),
                ('per_100g_sodium', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('per_100g_kcal', models.FloatField(default=0)),
                ('per_100g_carb', models.FloatField(default=0)),
                ('per_100g_protein', models.FloatField(default=0)),
                ('per_100g_fat', models.FloatField(default=0)),
                ('per_100g_sugar', models.FloatField(default=0)),
                ('per_100g_sodium', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'name'], name='nutrition_f_user_id_a1a0b7_idx')],
            },
        ),
    ]
