# Generated by Django 5.2.9 on 2025-12-24 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('energy_kcal', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sugars_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sodium_mg', models.DecimalField(decimal_places=1, default=0, max_digits=9)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='nutrition_f_name_caa2b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uq_food_name')],
            },
        ),
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('energy_kcal', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sugars_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sodium_mg', models.DecimalField(decimal_places=1, default=0, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'name'], name='nutrition_c_user_id_a0b6ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='uq_customfood_user_name')],
            },
        ),
        migrations.CreateModel(
            name='FoodFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('energy_kcal', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sugars_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sodium_mg', models.DecimalField(decimal_places=1, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='nutrition_f_user_id_ba826d_idx'), models.Index(fields=['user', 'name'], name='nutrition_f_user_id_a1a0b7_idx')],
            },
        ),
    ]
