# Generated by Django 5.2.9 on 2025-12-19 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('serving_g', models.FloatField(default=100.0)),
                ('kcal', models.FloatField()),
                ('carb_g', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('sugar_g', models.FloatField(default=0.0)),
                ('sodium_mg', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serving_g', models.FloatField(default=100.0)),
                ('kcal', models.FloatField()),
                ('carb_g', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('sugar_g', models.FloatField(default=0.0)),
                ('sodium_mg', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
