# Generated by Django 5.2.9 on 2025-12-22 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', '남'), ('F', '여'), ('O', '기타/선택안함')], default='O', max_length=1)),
                ('activity_level', models.CharField(choices=[('sedentary', '거의 안 함'), ('light', '가벼움(주 1~3회)'), ('moderate', '보통(주 3~5회)'), ('active', '활발(주 6~7회)'), ('very_active', '매우 활발(고강도/2회 이상)')], default='sedentary', max_length=20)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('start_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('goal_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
