# Generated by Django 5.2.9 on 2025-12-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_type',
            field=models.CharField(choices=[('maintain', '건강 유지'), ('loss', '체중감량(체지방 감소)'), ('gain', '근육량 증가(벌크업)')], default='maintain', max_length=20),
        ),
    ]
